//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CadeODinheiro.Web.WebServiceUserAuth {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.senior.com.br", ConfigurationName="WebServiceUserAuth.sapiens_SyncMCWFUsers")]
    public interface sapiens_SyncMCWFUsers {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.senior.com.br/sapiens_SyncMCWFUsers/UserReplicationRequest", ReplyAction="http://services.senior.com.br/sapiens_SyncMCWFUsers/UserReplicationResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        CadeODinheiro.Web.WebServiceUserAuth.mcwfUsersUserReplicationOut UserReplication(string user, string password, int encryption, CadeODinheiro.Web.WebServiceUserAuth.mcwfUsersUserReplicationIn parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.senior.com.br/sapiens_SyncMCWFUsers/UserReplicationRequest", ReplyAction="http://services.senior.com.br/sapiens_SyncMCWFUsers/UserReplicationResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        System.Threading.Tasks.Task<CadeODinheiro.Web.WebServiceUserAuth.mcwfUsersUserReplicationOut> UserReplicationAsync(string user, string password, int encryption, CadeODinheiro.Web.WebServiceUserAuth.mcwfUsersUserReplicationIn parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.senior.com.br/sapiens_SyncMCWFUsers/DiscoverUsersGroupsRequest", ReplyAction="http://services.senior.com.br/sapiens_SyncMCWFUsers/DiscoverUsersGroupsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        CadeODinheiro.Web.WebServiceUserAuth.mcwfUsersDiscoverUsersGroupsOut DiscoverUsersGroups(string user, string password, int encryption, CadeODinheiro.Web.WebServiceUserAuth.mcwfUsersDiscoverUsersGroupsIn parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.senior.com.br/sapiens_SyncMCWFUsers/DiscoverUsersGroupsRequest", ReplyAction="http://services.senior.com.br/sapiens_SyncMCWFUsers/DiscoverUsersGroupsResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        System.Threading.Tasks.Task<CadeODinheiro.Web.WebServiceUserAuth.mcwfUsersDiscoverUsersGroupsOut> DiscoverUsersGroupsAsync(string user, string password, int encryption, CadeODinheiro.Web.WebServiceUserAuth.mcwfUsersDiscoverUsersGroupsIn parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.senior.com.br/sapiens_SyncMCWFUsers/ChangePasswordRequest", ReplyAction="http://services.senior.com.br/sapiens_SyncMCWFUsers/ChangePasswordResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        CadeODinheiro.Web.WebServiceUserAuth.mcwfUsersChangePasswordOut ChangePassword(string user, string password, int encryption, CadeODinheiro.Web.WebServiceUserAuth.mcwfUsersChangePasswordIn parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.senior.com.br/sapiens_SyncMCWFUsers/ChangePasswordRequest", ReplyAction="http://services.senior.com.br/sapiens_SyncMCWFUsers/ChangePasswordResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        System.Threading.Tasks.Task<CadeODinheiro.Web.WebServiceUserAuth.mcwfUsersChangePasswordOut> ChangePasswordAsync(string user, string password, int encryption, CadeODinheiro.Web.WebServiceUserAuth.mcwfUsersChangePasswordIn parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.senior.com.br/sapiens_SyncMCWFUsers/AuthenticateJAASRequest", ReplyAction="http://services.senior.com.br/sapiens_SyncMCWFUsers/AuthenticateJAASResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        CadeODinheiro.Web.WebServiceUserAuth.mcwfUsersAuthenticateJAASOut AuthenticateJAAS(string user, string password, int encryption, CadeODinheiro.Web.WebServiceUserAuth.mcwfUsersAuthenticateJAASIn parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.senior.com.br/sapiens_SyncMCWFUsers/AuthenticateJAASRequest", ReplyAction="http://services.senior.com.br/sapiens_SyncMCWFUsers/AuthenticateJAASResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        System.Threading.Tasks.Task<CadeODinheiro.Web.WebServiceUserAuth.mcwfUsersAuthenticateJAASOut> AuthenticateJAASAsync(string user, string password, int encryption, CadeODinheiro.Web.WebServiceUserAuth.mcwfUsersAuthenticateJAASIn parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.senior.com.br/sapiens_SyncMCWFUsers/GetUserGroupsRequest", ReplyAction="http://services.senior.com.br/sapiens_SyncMCWFUsers/GetUserGroupsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        CadeODinheiro.Web.WebServiceUserAuth.mcwfUsersGetUserGroupsOut GetUserGroups(string user, string password, int encryption, CadeODinheiro.Web.WebServiceUserAuth.mcwfUsersGetUserGroupsIn parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.senior.com.br/sapiens_SyncMCWFUsers/GetUserGroupsRequest", ReplyAction="http://services.senior.com.br/sapiens_SyncMCWFUsers/GetUserGroupsResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        System.Threading.Tasks.Task<CadeODinheiro.Web.WebServiceUserAuth.mcwfUsersGetUserGroupsOut> GetUserGroupsAsync(string user, string password, int encryption, CadeODinheiro.Web.WebServiceUserAuth.mcwfUsersGetUserGroupsIn parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.senior.com.br/sapiens_SyncMCWFUsers/GetPersonKindRequest", ReplyAction="http://services.senior.com.br/sapiens_SyncMCWFUsers/GetPersonKindResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        CadeODinheiro.Web.WebServiceUserAuth.mcwfUsersGetPersonKindOut GetPersonKind(string user, string password, int encryption, CadeODinheiro.Web.WebServiceUserAuth.mcwfUsersGetPersonKindIn parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.senior.com.br/sapiens_SyncMCWFUsers/GetPersonKindRequest", ReplyAction="http://services.senior.com.br/sapiens_SyncMCWFUsers/GetPersonKindResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        System.Threading.Tasks.Task<CadeODinheiro.Web.WebServiceUserAuth.mcwfUsersGetPersonKindOut> GetPersonKindAsync(string user, string password, int encryption, CadeODinheiro.Web.WebServiceUserAuth.mcwfUsersGetPersonKindIn parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.senior.com.br/sapiens_SyncMCWFUsers/PersonExistsRequest", ReplyAction="http://services.senior.com.br/sapiens_SyncMCWFUsers/PersonExistsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        CadeODinheiro.Web.WebServiceUserAuth.mcwfUsersPersonExistsOut PersonExists(string user, string password, int encryption, CadeODinheiro.Web.WebServiceUserAuth.mcwfUsersPersonExistsIn parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.senior.com.br/sapiens_SyncMCWFUsers/PersonExistsRequest", ReplyAction="http://services.senior.com.br/sapiens_SyncMCWFUsers/PersonExistsResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        System.Threading.Tasks.Task<CadeODinheiro.Web.WebServiceUserAuth.mcwfUsersPersonExistsOut> PersonExistsAsync(string user, string password, int encryption, CadeODinheiro.Web.WebServiceUserAuth.mcwfUsersPersonExistsIn parameters);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.senior.com.br")]
    public partial class mcwfUsersUserReplicationIn : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string flowInstanceIDField;
        
        private string flowNameField;
        
        private string pmUserReplicationXMLField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string flowInstanceID {
            get {
                return this.flowInstanceIDField;
            }
            set {
                this.flowInstanceIDField = value;
                this.RaisePropertyChanged("flowInstanceID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string flowName {
            get {
                return this.flowNameField;
            }
            set {
                this.flowNameField = value;
                this.RaisePropertyChanged("flowName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string pmUserReplicationXML {
            get {
                return this.pmUserReplicationXMLField;
            }
            set {
                this.pmUserReplicationXMLField = value;
                this.RaisePropertyChanged("pmUserReplicationXML");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.senior.com.br")]
    public partial class mcwfUsersPersonExistsOut : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string erroExecucaoField;
        
        private string pmPersonExistsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string erroExecucao {
            get {
                return this.erroExecucaoField;
            }
            set {
                this.erroExecucaoField = value;
                this.RaisePropertyChanged("erroExecucao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string pmPersonExists {
            get {
                return this.pmPersonExistsField;
            }
            set {
                this.pmPersonExistsField = value;
                this.RaisePropertyChanged("pmPersonExists");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.senior.com.br")]
    public partial class mcwfUsersPersonExistsIn : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string flowInstanceIDField;
        
        private string flowNameField;
        
        private string pmPersonKindField;
        
        private string pmPersonNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string flowInstanceID {
            get {
                return this.flowInstanceIDField;
            }
            set {
                this.flowInstanceIDField = value;
                this.RaisePropertyChanged("flowInstanceID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string flowName {
            get {
                return this.flowNameField;
            }
            set {
                this.flowNameField = value;
                this.RaisePropertyChanged("flowName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string pmPersonKind {
            get {
                return this.pmPersonKindField;
            }
            set {
                this.pmPersonKindField = value;
                this.RaisePropertyChanged("pmPersonKind");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string pmPersonName {
            get {
                return this.pmPersonNameField;
            }
            set {
                this.pmPersonNameField = value;
                this.RaisePropertyChanged("pmPersonName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.senior.com.br")]
    public partial class mcwfUsersGetPersonKindOut : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string erroExecucaoField;
        
        private string pmPersonKindField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string erroExecucao {
            get {
                return this.erroExecucaoField;
            }
            set {
                this.erroExecucaoField = value;
                this.RaisePropertyChanged("erroExecucao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string pmPersonKind {
            get {
                return this.pmPersonKindField;
            }
            set {
                this.pmPersonKindField = value;
                this.RaisePropertyChanged("pmPersonKind");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.senior.com.br")]
    public partial class mcwfUsersGetPersonKindIn : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string flowInstanceIDField;
        
        private string flowNameField;
        
        private string pmPersonNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string flowInstanceID {
            get {
                return this.flowInstanceIDField;
            }
            set {
                this.flowInstanceIDField = value;
                this.RaisePropertyChanged("flowInstanceID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string flowName {
            get {
                return this.flowNameField;
            }
            set {
                this.flowNameField = value;
                this.RaisePropertyChanged("flowName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string pmPersonName {
            get {
                return this.pmPersonNameField;
            }
            set {
                this.pmPersonNameField = value;
                this.RaisePropertyChanged("pmPersonName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.senior.com.br")]
    public partial class mcwfUsersGetUserGroupsOut : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string erroExecucaoField;
        
        private string pmGetUserGroupsResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string erroExecucao {
            get {
                return this.erroExecucaoField;
            }
            set {
                this.erroExecucaoField = value;
                this.RaisePropertyChanged("erroExecucao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string pmGetUserGroupsResult {
            get {
                return this.pmGetUserGroupsResultField;
            }
            set {
                this.pmGetUserGroupsResultField = value;
                this.RaisePropertyChanged("pmGetUserGroupsResult");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.senior.com.br")]
    public partial class mcwfUsersGetUserGroupsIn : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string flowInstanceIDField;
        
        private string flowNameField;
        
        private string pmGetUserGroupsUserNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string flowInstanceID {
            get {
                return this.flowInstanceIDField;
            }
            set {
                this.flowInstanceIDField = value;
                this.RaisePropertyChanged("flowInstanceID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string flowName {
            get {
                return this.flowNameField;
            }
            set {
                this.flowNameField = value;
                this.RaisePropertyChanged("flowName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string pmGetUserGroupsUserName {
            get {
                return this.pmGetUserGroupsUserNameField;
            }
            set {
                this.pmGetUserGroupsUserNameField = value;
                this.RaisePropertyChanged("pmGetUserGroupsUserName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.senior.com.br")]
    public partial class mcwfUsersAuthenticateJAASOut : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string erroExecucaoField;
        
        private string pmLoggedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string erroExecucao {
            get {
                return this.erroExecucaoField;
            }
            set {
                this.erroExecucaoField = value;
                this.RaisePropertyChanged("erroExecucao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string pmLogged {
            get {
                return this.pmLoggedField;
            }
            set {
                this.pmLoggedField = value;
                this.RaisePropertyChanged("pmLogged");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.senior.com.br")]
    public partial class mcwfUsersAuthenticateJAASIn : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string flowInstanceIDField;
        
        private string flowNameField;
        
        private System.Nullable<int> pmEncryptedField;
        
        private bool pmEncryptedFieldSpecified;
        
        private string pmUserNameField;
        
        private string pmUserPasswordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string flowInstanceID {
            get {
                return this.flowInstanceIDField;
            }
            set {
                this.flowInstanceIDField = value;
                this.RaisePropertyChanged("flowInstanceID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string flowName {
            get {
                return this.flowNameField;
            }
            set {
                this.flowNameField = value;
                this.RaisePropertyChanged("flowName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public System.Nullable<int> pmEncrypted {
            get {
                return this.pmEncryptedField;
            }
            set {
                this.pmEncryptedField = value;
                this.RaisePropertyChanged("pmEncrypted");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pmEncryptedSpecified {
            get {
                return this.pmEncryptedFieldSpecified;
            }
            set {
                this.pmEncryptedFieldSpecified = value;
                this.RaisePropertyChanged("pmEncryptedSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string pmUserName {
            get {
                return this.pmUserNameField;
            }
            set {
                this.pmUserNameField = value;
                this.RaisePropertyChanged("pmUserName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public string pmUserPassword {
            get {
                return this.pmUserPasswordField;
            }
            set {
                this.pmUserPasswordField = value;
                this.RaisePropertyChanged("pmUserPassword");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.senior.com.br")]
    public partial class mcwfUsersChangePasswordOut : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string erroExecucaoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string erroExecucao {
            get {
                return this.erroExecucaoField;
            }
            set {
                this.erroExecucaoField = value;
                this.RaisePropertyChanged("erroExecucao");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.senior.com.br")]
    public partial class mcwfUsersChangePasswordIn : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string flowInstanceIDField;
        
        private string flowNameField;
        
        private string pmNewPasswordField;
        
        private string pmNewPasswordConfirmationField;
        
        private string pmPasswordField;
        
        private string pmUserField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string flowInstanceID {
            get {
                return this.flowInstanceIDField;
            }
            set {
                this.flowInstanceIDField = value;
                this.RaisePropertyChanged("flowInstanceID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string flowName {
            get {
                return this.flowNameField;
            }
            set {
                this.flowNameField = value;
                this.RaisePropertyChanged("flowName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string pmNewPassword {
            get {
                return this.pmNewPasswordField;
            }
            set {
                this.pmNewPasswordField = value;
                this.RaisePropertyChanged("pmNewPassword");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string pmNewPasswordConfirmation {
            get {
                return this.pmNewPasswordConfirmationField;
            }
            set {
                this.pmNewPasswordConfirmationField = value;
                this.RaisePropertyChanged("pmNewPasswordConfirmation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public string pmPassword {
            get {
                return this.pmPasswordField;
            }
            set {
                this.pmPasswordField = value;
                this.RaisePropertyChanged("pmPassword");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public string pmUser {
            get {
                return this.pmUserField;
            }
            set {
                this.pmUserField = value;
                this.RaisePropertyChanged("pmUser");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.senior.com.br")]
    public partial class mcwfUsersDiscoverUsersGroupsOut : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string erroExecucaoField;
        
        private string pmReturnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string erroExecucao {
            get {
                return this.erroExecucaoField;
            }
            set {
                this.erroExecucaoField = value;
                this.RaisePropertyChanged("erroExecucao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string pmReturn {
            get {
                return this.pmReturnField;
            }
            set {
                this.pmReturnField = value;
                this.RaisePropertyChanged("pmReturn");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.senior.com.br")]
    public partial class mcwfUsersDiscoverUsersGroupsIn : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string flowInstanceIDField;
        
        private string flowNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string flowInstanceID {
            get {
                return this.flowInstanceIDField;
            }
            set {
                this.flowInstanceIDField = value;
                this.RaisePropertyChanged("flowInstanceID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string flowName {
            get {
                return this.flowNameField;
            }
            set {
                this.flowNameField = value;
                this.RaisePropertyChanged("flowName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.senior.com.br")]
    public partial class mcwfUsersUserReplicationOut : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string erroExecucaoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string erroExecucao {
            get {
                return this.erroExecucaoField;
            }
            set {
                this.erroExecucaoField = value;
                this.RaisePropertyChanged("erroExecucao");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface sapiens_SyncMCWFUsersChannel : CadeODinheiro.Web.WebServiceUserAuth.sapiens_SyncMCWFUsers, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class sapiens_SyncMCWFUsersClient : System.ServiceModel.ClientBase<CadeODinheiro.Web.WebServiceUserAuth.sapiens_SyncMCWFUsers>, CadeODinheiro.Web.WebServiceUserAuth.sapiens_SyncMCWFUsers {
        
        public sapiens_SyncMCWFUsersClient() {
        }
        
        public sapiens_SyncMCWFUsersClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public sapiens_SyncMCWFUsersClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public sapiens_SyncMCWFUsersClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public sapiens_SyncMCWFUsersClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CadeODinheiro.Web.WebServiceUserAuth.mcwfUsersUserReplicationOut UserReplication(string user, string password, int encryption, CadeODinheiro.Web.WebServiceUserAuth.mcwfUsersUserReplicationIn parameters) {
            return base.Channel.UserReplication(user, password, encryption, parameters);
        }
        
        public System.Threading.Tasks.Task<CadeODinheiro.Web.WebServiceUserAuth.mcwfUsersUserReplicationOut> UserReplicationAsync(string user, string password, int encryption, CadeODinheiro.Web.WebServiceUserAuth.mcwfUsersUserReplicationIn parameters) {
            return base.Channel.UserReplicationAsync(user, password, encryption, parameters);
        }
        
        public CadeODinheiro.Web.WebServiceUserAuth.mcwfUsersDiscoverUsersGroupsOut DiscoverUsersGroups(string user, string password, int encryption, CadeODinheiro.Web.WebServiceUserAuth.mcwfUsersDiscoverUsersGroupsIn parameters) {
            return base.Channel.DiscoverUsersGroups(user, password, encryption, parameters);
        }
        
        public System.Threading.Tasks.Task<CadeODinheiro.Web.WebServiceUserAuth.mcwfUsersDiscoverUsersGroupsOut> DiscoverUsersGroupsAsync(string user, string password, int encryption, CadeODinheiro.Web.WebServiceUserAuth.mcwfUsersDiscoverUsersGroupsIn parameters) {
            return base.Channel.DiscoverUsersGroupsAsync(user, password, encryption, parameters);
        }
        
        public CadeODinheiro.Web.WebServiceUserAuth.mcwfUsersChangePasswordOut ChangePassword(string user, string password, int encryption, CadeODinheiro.Web.WebServiceUserAuth.mcwfUsersChangePasswordIn parameters) {
            return base.Channel.ChangePassword(user, password, encryption, parameters);
        }
        
        public System.Threading.Tasks.Task<CadeODinheiro.Web.WebServiceUserAuth.mcwfUsersChangePasswordOut> ChangePasswordAsync(string user, string password, int encryption, CadeODinheiro.Web.WebServiceUserAuth.mcwfUsersChangePasswordIn parameters) {
            return base.Channel.ChangePasswordAsync(user, password, encryption, parameters);
        }
        
        public CadeODinheiro.Web.WebServiceUserAuth.mcwfUsersAuthenticateJAASOut AuthenticateJAAS(string user, string password, int encryption, CadeODinheiro.Web.WebServiceUserAuth.mcwfUsersAuthenticateJAASIn parameters) {
            return base.Channel.AuthenticateJAAS(user, password, encryption, parameters);
        }
        
        public System.Threading.Tasks.Task<CadeODinheiro.Web.WebServiceUserAuth.mcwfUsersAuthenticateJAASOut> AuthenticateJAASAsync(string user, string password, int encryption, CadeODinheiro.Web.WebServiceUserAuth.mcwfUsersAuthenticateJAASIn parameters) {
            return base.Channel.AuthenticateJAASAsync(user, password, encryption, parameters);
        }
        
        public CadeODinheiro.Web.WebServiceUserAuth.mcwfUsersGetUserGroupsOut GetUserGroups(string user, string password, int encryption, CadeODinheiro.Web.WebServiceUserAuth.mcwfUsersGetUserGroupsIn parameters) {
            return base.Channel.GetUserGroups(user, password, encryption, parameters);
        }
        
        public System.Threading.Tasks.Task<CadeODinheiro.Web.WebServiceUserAuth.mcwfUsersGetUserGroupsOut> GetUserGroupsAsync(string user, string password, int encryption, CadeODinheiro.Web.WebServiceUserAuth.mcwfUsersGetUserGroupsIn parameters) {
            return base.Channel.GetUserGroupsAsync(user, password, encryption, parameters);
        }
        
        public CadeODinheiro.Web.WebServiceUserAuth.mcwfUsersGetPersonKindOut GetPersonKind(string user, string password, int encryption, CadeODinheiro.Web.WebServiceUserAuth.mcwfUsersGetPersonKindIn parameters) {
            return base.Channel.GetPersonKind(user, password, encryption, parameters);
        }
        
        public System.Threading.Tasks.Task<CadeODinheiro.Web.WebServiceUserAuth.mcwfUsersGetPersonKindOut> GetPersonKindAsync(string user, string password, int encryption, CadeODinheiro.Web.WebServiceUserAuth.mcwfUsersGetPersonKindIn parameters) {
            return base.Channel.GetPersonKindAsync(user, password, encryption, parameters);
        }
        
        public CadeODinheiro.Web.WebServiceUserAuth.mcwfUsersPersonExistsOut PersonExists(string user, string password, int encryption, CadeODinheiro.Web.WebServiceUserAuth.mcwfUsersPersonExistsIn parameters) {
            return base.Channel.PersonExists(user, password, encryption, parameters);
        }
        
        public System.Threading.Tasks.Task<CadeODinheiro.Web.WebServiceUserAuth.mcwfUsersPersonExistsOut> PersonExistsAsync(string user, string password, int encryption, CadeODinheiro.Web.WebServiceUserAuth.mcwfUsersPersonExistsIn parameters) {
            return base.Channel.PersonExistsAsync(user, password, encryption, parameters);
        }
    }
}
