//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CadeODinheiro.Web.WebServicePatrimonio {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.senior.com.br", ConfigurationName="WebServicePatrimonio.sapiens_Synccom_tbos_pat_carregabens")]
    public interface sapiens_Synccom_tbos_pat_carregabens {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.senior.com.br/sapiens_Synccom_tbos_pat_carregabens/buscadadosRequ" +
            "est", ReplyAction="http://services.senior.com.br/sapiens_Synccom_tbos_pat_carregabens/buscadadosResp" +
            "onse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        CadeODinheiro.Web.WebServicePatrimonio.carregabensbuscadadosOut buscadados(string user, string password, int encryption, CadeODinheiro.Web.WebServicePatrimonio.carregabensbuscadadosIn parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.senior.com.br/sapiens_Synccom_tbos_pat_carregabens/buscadadosRequ" +
            "est", ReplyAction="http://services.senior.com.br/sapiens_Synccom_tbos_pat_carregabens/buscadadosResp" +
            "onse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        System.Threading.Tasks.Task<CadeODinheiro.Web.WebServicePatrimonio.carregabensbuscadadosOut> buscadadosAsync(string user, string password, int encryption, CadeODinheiro.Web.WebServicePatrimonio.carregabensbuscadadosIn parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.senior.com.br/sapiens_Synccom_tbos_pat_carregabens/carreganomeReq" +
            "uest", ReplyAction="http://services.senior.com.br/sapiens_Synccom_tbos_pat_carregabens/carreganomeRes" +
            "ponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        CadeODinheiro.Web.WebServicePatrimonio.carregabenscarreganomeOut carreganome(string user, string password, int encryption, CadeODinheiro.Web.WebServicePatrimonio.carregabenscarreganomeIn parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.senior.com.br/sapiens_Synccom_tbos_pat_carregabens/carreganomeReq" +
            "uest", ReplyAction="http://services.senior.com.br/sapiens_Synccom_tbos_pat_carregabens/carreganomeRes" +
            "ponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        System.Threading.Tasks.Task<CadeODinheiro.Web.WebServicePatrimonio.carregabenscarreganomeOut> carreganomeAsync(string user, string password, int encryption, CadeODinheiro.Web.WebServicePatrimonio.carregabenscarreganomeIn parameters);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.senior.com.br")]
    public partial class carregabensbuscadadosIn : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<int> codEmpField;
        
        private bool codEmpFieldSpecified;
        
        private string flowInstanceIDField;
        
        private string flowNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public System.Nullable<int> codEmp {
            get {
                return this.codEmpField;
            }
            set {
                this.codEmpField = value;
                this.RaisePropertyChanged("codEmp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codEmpSpecified {
            get {
                return this.codEmpFieldSpecified;
            }
            set {
                this.codEmpFieldSpecified = value;
                this.RaisePropertyChanged("codEmpSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string flowInstanceID {
            get {
                return this.flowInstanceIDField;
            }
            set {
                this.flowInstanceIDField = value;
                this.RaisePropertyChanged("flowInstanceID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string flowName {
            get {
                return this.flowNameField;
            }
            set {
                this.flowNameField = value;
                this.RaisePropertyChanged("flowName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.senior.com.br")]
    public partial class carregabenscarreganomeOut : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string erroExecucaoField;
        
        private string msgRetornoField;
        
        private string nomComField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string erroExecucao {
            get {
                return this.erroExecucaoField;
            }
            set {
                this.erroExecucaoField = value;
                this.RaisePropertyChanged("erroExecucao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string msgRetorno {
            get {
                return this.msgRetornoField;
            }
            set {
                this.msgRetornoField = value;
                this.RaisePropertyChanged("msgRetorno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string nomCom {
            get {
                return this.nomComField;
            }
            set {
                this.nomComField = value;
                this.RaisePropertyChanged("nomCom");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.senior.com.br")]
    public partial class carregabenscarreganomeIn : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string flowInstanceIDField;
        
        private string flowNameField;
        
        private string nomUsuField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string flowInstanceID {
            get {
                return this.flowInstanceIDField;
            }
            set {
                this.flowInstanceIDField = value;
                this.RaisePropertyChanged("flowInstanceID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string flowName {
            get {
                return this.flowNameField;
            }
            set {
                this.flowNameField = value;
                this.RaisePropertyChanged("flowName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string nomUsu {
            get {
                return this.nomUsuField;
            }
            set {
                this.nomUsuField = value;
                this.RaisePropertyChanged("nomUsu");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.senior.com.br")]
    public partial class carregabensbuscadadosOutLocais : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<int> codFilField;
        
        private bool codFilFieldSpecified;
        
        private string codLocField;
        
        private string nomLocField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public System.Nullable<int> codFil {
            get {
                return this.codFilField;
            }
            set {
                this.codFilField = value;
                this.RaisePropertyChanged("codFil");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codFilSpecified {
            get {
                return this.codFilFieldSpecified;
            }
            set {
                this.codFilFieldSpecified = value;
                this.RaisePropertyChanged("codFilSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string codLoc {
            get {
                return this.codLocField;
            }
            set {
                this.codLocField = value;
                this.RaisePropertyChanged("codLoc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string nomLoc {
            get {
                return this.nomLocField;
            }
            set {
                this.nomLocField = value;
                this.RaisePropertyChanged("nomLoc");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.senior.com.br")]
    public partial class carregabensbuscadadosOutCentrosCusto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codCcuField;
        
        private string desCcuField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string codCcu {
            get {
                return this.codCcuField;
            }
            set {
                this.codCcuField = value;
                this.RaisePropertyChanged("codCcu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string desCcu {
            get {
                return this.desCcuField;
            }
            set {
                this.desCcuField = value;
                this.RaisePropertyChanged("desCcu");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.senior.com.br")]
    public partial class carregabensbuscadadosOutBens : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codBarField;
        
        private string codBemField;
        
        private string codCcuField;
        
        private System.Nullable<int> codFilField;
        
        private bool codFilFieldSpecified;
        
        private string codLocField;
        
        private string desBemField;
        
        private string numPlaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string codBar {
            get {
                return this.codBarField;
            }
            set {
                this.codBarField = value;
                this.RaisePropertyChanged("codBar");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string codBem {
            get {
                return this.codBemField;
            }
            set {
                this.codBemField = value;
                this.RaisePropertyChanged("codBem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string codCcu {
            get {
                return this.codCcuField;
            }
            set {
                this.codCcuField = value;
                this.RaisePropertyChanged("codCcu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public System.Nullable<int> codFil {
            get {
                return this.codFilField;
            }
            set {
                this.codFilField = value;
                this.RaisePropertyChanged("codFil");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codFilSpecified {
            get {
                return this.codFilFieldSpecified;
            }
            set {
                this.codFilFieldSpecified = value;
                this.RaisePropertyChanged("codFilSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public string codLoc {
            get {
                return this.codLocField;
            }
            set {
                this.codLocField = value;
                this.RaisePropertyChanged("codLoc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public string desBem {
            get {
                return this.desBemField;
            }
            set {
                this.desBemField = value;
                this.RaisePropertyChanged("desBem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=6)]
        public string numPla {
            get {
                return this.numPlaField;
            }
            set {
                this.numPlaField = value;
                this.RaisePropertyChanged("numPla");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.senior.com.br")]
    public partial class carregabensbuscadadosOut : object, System.ComponentModel.INotifyPropertyChanged {
        
        private carregabensbuscadadosOutBens[] bensField;
        
        private carregabensbuscadadosOutCentrosCusto[] centrosCustoField;
        
        private string erroExecucaoField;
        
        private carregabensbuscadadosOutLocais[] locaisField;
        
        private string msgRetornoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("bens", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public carregabensbuscadadosOutBens[] bens {
            get {
                return this.bensField;
            }
            set {
                this.bensField = value;
                this.RaisePropertyChanged("bens");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("centrosCusto", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public carregabensbuscadadosOutCentrosCusto[] centrosCusto {
            get {
                return this.centrosCustoField;
            }
            set {
                this.centrosCustoField = value;
                this.RaisePropertyChanged("centrosCusto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string erroExecucao {
            get {
                return this.erroExecucaoField;
            }
            set {
                this.erroExecucaoField = value;
                this.RaisePropertyChanged("erroExecucao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("locais", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public carregabensbuscadadosOutLocais[] locais {
            get {
                return this.locaisField;
            }
            set {
                this.locaisField = value;
                this.RaisePropertyChanged("locais");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public string msgRetorno {
            get {
                return this.msgRetornoField;
            }
            set {
                this.msgRetornoField = value;
                this.RaisePropertyChanged("msgRetorno");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface sapiens_Synccom_tbos_pat_carregabensChannel : CadeODinheiro.Web.WebServicePatrimonio.sapiens_Synccom_tbos_pat_carregabens, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class sapiens_Synccom_tbos_pat_carregabensClient : System.ServiceModel.ClientBase<CadeODinheiro.Web.WebServicePatrimonio.sapiens_Synccom_tbos_pat_carregabens>, CadeODinheiro.Web.WebServicePatrimonio.sapiens_Synccom_tbos_pat_carregabens {
        
        public sapiens_Synccom_tbos_pat_carregabensClient() {
        }
        
        public sapiens_Synccom_tbos_pat_carregabensClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public sapiens_Synccom_tbos_pat_carregabensClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public sapiens_Synccom_tbos_pat_carregabensClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public sapiens_Synccom_tbos_pat_carregabensClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CadeODinheiro.Web.WebServicePatrimonio.carregabensbuscadadosOut buscadados(string user, string password, int encryption, CadeODinheiro.Web.WebServicePatrimonio.carregabensbuscadadosIn parameters) {
            return base.Channel.buscadados(user, password, encryption, parameters);
        }
        
        public System.Threading.Tasks.Task<CadeODinheiro.Web.WebServicePatrimonio.carregabensbuscadadosOut> buscadadosAsync(string user, string password, int encryption, CadeODinheiro.Web.WebServicePatrimonio.carregabensbuscadadosIn parameters) {
            return base.Channel.buscadadosAsync(user, password, encryption, parameters);
        }
        
        public CadeODinheiro.Web.WebServicePatrimonio.carregabenscarreganomeOut carreganome(string user, string password, int encryption, CadeODinheiro.Web.WebServicePatrimonio.carregabenscarreganomeIn parameters) {
            return base.Channel.carreganome(user, password, encryption, parameters);
        }
        
        public System.Threading.Tasks.Task<CadeODinheiro.Web.WebServicePatrimonio.carregabenscarreganomeOut> carreganomeAsync(string user, string password, int encryption, CadeODinheiro.Web.WebServicePatrimonio.carregabenscarreganomeIn parameters) {
            return base.Channel.carreganomeAsync(user, password, encryption, parameters);
        }
    }
}
