// <auto-generated />
namespace CadeODinheiro.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class v3DB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v3DB));
        
        string IMigrationMetadata.Id
        {
            get { return "201409201647591_v3DB"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
